### ISSUE TITLE
Crashes on add and remove in anki 2.1.29

### ISSUE THREAD

**Issue by 0skr** [IllDepence/anki_add_pitch_plugin#4]
When pressing Tools>Pitch Accent>remove or Tools>Pitch Accent>add anki gives the two following error messages respectively.

Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-30 21:40:18
Add-ons possibly involved: ⁨Japanese Pitch Accent⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/oskar/Library/Application Support/Anki2/addons21/148002038/__init__.py", line 75, in remove_pitch_dialog
    deck_id = pa_util.select_deck_id(
  File "/Users/oskar/Library/Application Support/Anki2/addons21/148002038/util.py", line 14, in select_deck_id
    deks = json.loads(row[0])
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/

Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-30 21:40:18
Add-ons possibly involved: ⁨Japanese Pitch Accent⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/oskar/Library/Application Support/Anki2/addons21/148002038/__init__.py", line 37, in add_pitch_dialog
    deck_id = pa_util.select_deck_id('Which deck would you like to extend?')
  File "/Users/oskar/Library/Application Support/Anki2/addons21/148002038/util.py", line 14, in select_deck_id
    deks = json.loads(row[0])
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by IllDepence** [comment]
Thanks for the report.

I just upgraded to 2.1.29 and confirmed the issue. Will look into it and keep you updated.

**Comment by IllDepence** [comment]
Should be fixed now.

Can you confirm that it's working for you as well?

**Comment by 0skr** [comment]
it is indeed working as expected now! thanks for an amazing add-on

**Comment by IllDepence** [comment]
Thanks for the confirmation and the kind words.
Glad you like the add-on. (‌:
